title: Phone Box Theatre
email: hello@phoneboxtheatre.co.uk 
contacts: 
  - name: Email 
    link: mailto:hello@phoneboxtheatre.co.uk 
    icon: fa fa-envelope
  - name: Facebook 
    link: https://facebook.com/phoneboxtheatre/
    icon: fab fa-facebook  
  - name: Twitter 
    link: https://twitter.com/phoneboxtheatre/
    icon: fab fa-twitter
  - name: Instagram
    link: https://Instagram.com/phoneboxtheatre/
    icon: fab fa-instagram 
description: >- # this means to ignore newlines until "baseurl:"
  Phone Box Theatre is a new, independent theatre company based in the East Midlands. We create work focused on connecting others with high quality technical design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  samozzy


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

strict_front_matter: true 
livereload: true 

plugins:
  - bootstrap 

sass:
    sass_dir: _sass
    style: expanded 

collections:
  content:
    output: true
    permalink: :path/
permalink: pretty 

defaults:
  # Defaults for pages
  - scope:
      type: content
    values:
      layout: default
